reset;
include modelFile.mod;
data parameters.dat;

#settings
#--------------------------------
let T := 200;
let nrOfSim := 1000;
let {i in 1..I} xStart[i] := 0;
#--------------------------------

solve AFred;
let {i in 1..I} VAFsim[i] := VAF[i];
let thetaAFsim := thetaAF;

include simulation.run;

display thetaAFsim;
display VAFsim;
display averageReward;
display confidence;
